services:
  gateway:
    image: nginx:latest
    container_name: gateway
    ports:
      - "80:80"
    networks:
      - app-net
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - auth-service
      - tasks-service

  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - app-net
    volumes:
      - postgres-data:/var/lib/postgresql/data

  auth-service:
    image: kostyabet228/crm-system:auth_service-latest
    container_name: auth-service
    networks:
      - app-net
    expose:
      - "5000"
    depends_on:
      - db
    environment:
      ACCESSTOKENSECRET: ${ACCESSTOKENSECRET}
      REFRESHTOKENSECRET: ${REFRESHTOKENSECRET}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}

  tasks-service:
    image: kostyabet228/crm-system:tasks_service-latest
    container_name: tasks-service
    networks:
      - app-net
    expose:
      - "5001"
    depends_on:
      - db
    environment:
      ACCESSTOKENSECRET: ${ACCESSTOKENSECRET}
      REFRESHTOKENSECRET: ${REFRESHTOKENSECRET}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      GATEWAY_URL: http:/gateway:80

  frontend:
    image: kostyabet228/crm-system:frontend-latest
    container_name: frontend
    networks:
      - app-net
    ports:
      - "3000:3000"
    environment:
      VITE_API_LOCAL: http:/gateway:80

networks:
  app-net:
    driver: bridge

volumes:
  postgres-data: {}