version: "3.8"

services:
  gateway:
    image: nginx:latest
    container_name: gateway
    ports:
      - "80:80"
    networks:
      - app-net
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - auth-service

  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - app-net
    volumes:
      - postgres-data:/var/lib/postgresql/data

  auth-service:
    image: kostyabet228/crm-system:auth_service-latest
    container_name: auth-service
    networks:
      - app-net
    expose:
      - "5000"
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres

  frontend:
    image: kostyabet228/crm-system:frontend-latest
    container_name: frontend
    networks:
      - app-net
    expose:
      - "80"

networks:
  app-net:
    driver: bridge

volumes:
  postgres-data: {}