export const TASK_BY_ID_QUERY_KEY = "TASK_BY_ID"
export const TASK_STATES_QUERY_KEY = "TASK_STATES"
export const TASK_PRIORITIES_QUERY_KEY = "TASK_PRIORITIES"
export const USER_TASKS_BY_ID_QUERY_KEY = 'USER_TASKS_BY_ID'
export const TASKS_QUERY_KEY = "TASKS"
export const PROJECTS_SUMMARY_QUERY_KEY = "PROJECTS_SUMMARY"