name: Build and Push Auth Servise Docker Image

on:
  push:
    branches:
      - auth_service
  pull_request:
    branches:
      - auth_service

env:
  NODE_VERSION: '20.18.0'
  IMAGE_NAME: kostyabet228/crm-system
  IMAGE_TAG: auth_service-latest

jobs:
  push:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: authorization/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}