name: Deploy Stack from Docker Hub

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
        - name: Checkout repo (for docker-compose.yml)
          uses: actions/checkout@v3
  
        - name: Set up Docker
          uses: docker/setup-buildx-action@v3

        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        
        - name: Pull latest images
          run: |
            docker pull kostyabet228/crm-system:auth_service-latest
            docker pull kostyabet228/crm-system:getaway-latest
            docker pull kostyabet228/crm-system:frontend-latest
  
        - name: Start stack with Docker Compose
          run: docker-compose up -d
