name: Build and Push Frontend Docker Image

on:
  push:
    branches:
      - frontend
  pull_request:
    branches:
      - frontend

env:
  NODE_VERSION: '20.18.0'
  IMAGE_NAME: kostyabet228/crm-system
  IMAGE_TAG: frontend-latest

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: |
            cd frontend
            npm install --legacy-peer-deps
  
      - name: Build project
        run: |
            cd frontend
            npm run build
  
  push:
    needs: build
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: |
            cd frontend
            npm install --legacy-peer-deps
  
      - name: Build project
        run: |
            cd frontend
            npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: frontend/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}